### ISSUE TITLE
add-vpc improvements

### ISSUE THREAD

**Issue by awick** [arkime/cloud-demo#21]
A few minor improvements for add-vpc command
* currently the name field is empty for the tms (traffic mirror session) and tmf (traffic mirror filter) use the vpc-id or vpc name
* currently the vni is always 123 for the tms, allow a optional --vni param or use unique (or random values)

**Comment by chelma** [comment]
Thanks!  Added it to the backlog.

**Comment by chelma** [comment]
Resolved in https://github.com/arkime/cloud-demo/pull/26
