### ISSUE TITLE
[Design Proposal] New Project Name

### ISSUE THREAD

**Issue by chelma** [arkime/cloud-demo#47]
## Background
This project is currently operating with the un-inspiring name "Cloud Demo".  A cooler name would give the project some pizzazz and personality.

## Proposed Names
As a vast and influential body of work, J. R. R. Tolkien's universe seems a suitable place to draw a name from.  It also happens to be the proposal writer's favorite legendarium.  A few naming suggestions based on that legendarium are as follows.  Care was taken to choose names that are thematically appropriate for the project's nature as a cloud-native security/analysis tool.

The proposal writer's pick is Gwaihir, with Manwe as a close second.  Earendil is an awesome name but it's more cumbersome.

### Manwe (MAN-weh)
* Manwë is the the king of the gods in Tolkien’s universe, lord of the winds, skies, and clouds, and has incredible sight.  Manwë is a chief advocate for Elves and Men among the gods, and watches over them.  A recurring theme within Tolkien's works is the expression of the gods' (and Manwë's) favor/disfavor as a "change in the winds" or the appearance of cloud formations.  
* The name plays on the themes of "cloud", "vision", and "protection".  It's also short, reasonable easy to pronounce, an unlikely to collide with the name of other projects or tools.
* From the Silmarillion: _“Of all the Great Ones who dwell in this world the Elves hold Manwë most in reverence and love. He is the Lord of the Breath of Arda, and all Middle-earth pays homage to him. [...] He is the winds’ master, and the mountain’s head, and the king of all the Valar. In his hand are the foundations of the earth, and the heights of the sky; and though he cannot be seen, he is near at hand. [...] For Manwë sees afar, and his eye pierces the mist, and even the Hidden cannot elude his gaze.”_

### Earendil (eh-ah-REN-dil)
* Eärendil is a key figure in Tolkien's works, so we'll keep it short here.  The most skilled of mariners, of both Elven and Human parentage, he navigated the cursed seas that separated the land of the Gods from the land of Mortals to seek their aid and save both Elves and Men from the conquering evil of Morgoth (Sauron's original master).  His actions saved Middle Earth from Morgoth's corruption and afterwards he sails the heavens in a flying ship with the light of the Gods on his brow as a symbol of hope for Middle Earth.
* The name plays on the themes of the sky, hope, navigation, and the defeat of evil.  It's a bit more popular of a name, but still seems likely to collide.  However, it is harder to pronounce.
* From the Silmarillion: _"Hail Eärendil, of mariners most renowned, the looked for that cometh at unawares, the longed for that cometh beyond hope! Hail Eärendil, bearer of light before the Sun and Moon! Splendour of the Children of Earth, star in the darkness, jewel in the sunset, radiant in the morning!"_

### Gwaihir (GWY-heer)
* Gwaihir is the King of the Eagles in the Lord of the Rings, and flies Gandalf around Middle Earth on several critical occasions (most notably to save Frodo and Sam after they toss the Ring into Orodruin).  He also led his kin to fight against the forces of Mordor in aid of Aragorn and Gondor during the final battle with Sauron.  As a symbol within Tolkien's works, Eagles represent Manwe's and the other gods' continued involvement with and support of Elves and Men against the forces of evil.
* The name plays on the themes of protection, oversight, aid, and "cloud-nativeness".  It's short, moderately easy to pronounce, and is unlikely to collide with other names.  It also sounds cool when said aloud (in the proposal writer's opinion).

**Comment by awick** [comment]
Since Arkime uses owls everywhere of the 3 I definitely prefer Gwaihir since both Owls and Eagles are Raptors. :) I tried to ask ChatGPT if there were any owls in Tolkien's work, but it was no help.

**Comment by chelma** [comment]
I'm down w/ Gwaihir.  To my knowledge (as someone who has read them numerous times), the word "owl" does not appear in The Hobbit, The Lord of the Rings, and The Silmarillion so it's unsurprising it was unable to suggest anything.

**Comment by awick** [comment]
A friend recommend that we should try and get ChatGPT to hallucinate and ask it questions like "What would Tolkien name an owl who loved clouds" and other similar things.

If we do go with a name that doesn't map to functionality, we should make sure it is clear somehow that it is an aws cloud deployer.

**Comment by chelma** [comment]
We could probably do something like that.  Have it adopt a persona that is an expert in Tolkien lore and Elvish languages and ask for variations on "cloud-lover" or "night-bird" in Sindarin.  Will try!

**Comment by chelma** [comment]
Yeah, I tried, and it DEFINITELY hallucinated.  Double-checking against an online Tolkien dictionary, some of its thinking was correct and other parts were completely made up.  Also, the fake/wrong words it suggested don't sound nearly as good as "Gwaihir" - lóminóti, alphdhû.  The online dictionary said there was a pre-made word for owl in Quenya ("hó") but I don't think that's the best pick for our project (lol!).

Wish there was an easier way to export ChatGPT convos... https://pastebin.com/RXJ85k8v

**Comment by awick** [comment]
lol, it is fun to mess with. This is the best I could get, which I have no clue is accurate or not. :)

Certainly! Here's a potential word for "owl supreme cloud protector" that you might find suitable:

Aelurcuma (pronounced: "ay-lur-KOO-ma")

This word is composed of three elements:

Aelu-: derived from the Quenya word "ael," which means "supreme" or "highest."
-rcum: taken from the Sindarin word "galvorn," which means "cloudy," with the initial "g" replaced by "r" for ease of pronunciation.
-a: a suffix used to create a noun from the previous elements.

**Comment by chelma** [comment]
Typically, it's a bad sign to directly mix/match Quenya and Sindarin.  While Sindarin is derived from Quenya, its spellings and rules are sufficiently different that they shouldn't be mixed/matched.  Furthermore, I think you'd offend every Elf in earshot to combine the two due to historical reasons.  Also, from memory, *galvorn* doesn't mean cloudy; it was the name of a specific metal alloy created by Eol, the Dark Elf.

**Comment by chelma** [comment]
So, are you thinking we should add a suffix or something to the project name to better indicate its purpose and contents?  Something like "gwaihir-cli" or "gwaihir-control-plane"?

**Comment by awick** [comment]
First of all, naming is always hard. 

If this was a standalone project I would be fine with "gwaihir". However since it is part of Arkime I wonder if it should have a non descriptive name? capture/viewer/cont3xt most folks get from the name. Parliament is understandable if you know that is the name of a group of owls. WISE, not so much, we probably should have named intel-agg or something.

Does "gwaihir" by itself mean anything? If we were developing the new hotness on deploying security tools to the cloud, then it doesn't matter. But since I think the focus is Arkime to the cloud or maybe even Arkime to AWS, maybe it should have a more tailored name?

Would something like "arkime/gwaihir-aws-deployer" make sense? Should it just be "arkime/aws-deployer"? (Just using aws-deployer as place holder for a descriptive name)

**Comment by chelma** [comment]
Point well-taken; `arkime/gwaihir` is pretty cryptic in terms of intent.  `gwaihir` doesn't add additional contextual value when placed under the `arkime` product banner and instead conflicts with the branding.  Maybe we'll find a different context to use the `gwaihir` name in.

Removing `gwaihir` from the conversation, I think the existing project is more than an `aws-deployer`; it's turning into a full-fledged control plane.  What about one of these options:

* `arkime/aws-control-plane`
* `arkime/aws-aio` (AIO -> All In One)
* `arkime/aws-monitoring`

I'm personally leaning towards `arkime/aws-aio`, as we are bundling development tools with a control plane mechanism.

**Comment by chelma** [comment]
Per discussion w/ @awick, `arkime/aws-aio` seems like a reasonable pick for the time being.  Can always change it later!
